# -*- coding: utf-8 -*-
"""Computational Aerodynamics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NBg2NmWNfAQzLcCfDR5cZuvcFFtzqkk
"""

import numpy as np
import matplotlib.pyplot as plt

def check(label, got, want, tol=0.01):
    if got is None:
        print(f"[  ] {label}: not attempted yet")
        return False
    ok = abs(got - want) <= tol * max(abs(want), 1e-9)
    mark = "PASS" if ok else "FAIL"
    print(f"[{mark}] {label}\n       you got {got:.4f}   expected {want:.4f}")
    if not ok:
        print("       -> check your formula and units")
    return ok

print("Setup complete. You're ready.")

rho = 1.225      # air density, kg/m^3
V   = 15.0       # speed, m/s
CLA = 3.5        # C_L * A, m^2

q = 0.5 * rho * V**2
F = q * CLA

print("dynamic pressure:", q, "Pa")
print("downforce:       ", F, "N")

V_hairpin = 10          # TODO: the speed, in m/s
q_hairpin = 61.25          # TODO: q = 0.5 * rho * V**2
F_hairpin = 214.375          # TODO: downforce = q * CLA

print(q_hairpin, F_hairpin)

check("q at 10 m/s",         q_hairpin, 61.25)
check("downforce at 10 m/s", F_hairpin, 214.375)

mass = 300.0
g    = 9.81

weight = 2943        # TODO: mass * g
pct    = 7.284        # TODO: 100 * F_hairpin / weight

print("weight:", weight, "N")
print("downforce is", pct, "% of car weight")

check("car weight", weight, 2943.0)
check("percent of weight at 10 m/s", pct, 7.284)

def double(x):
    return 2 * x

double(7)     # -> 14

rho = 1.225
CLA = 3.5

def dynamic_pressure(V):
    # TODO: return 0.5 * rho * V**2
    return 0.5 * rho * V**2

def downforce(V):
    # TODO: call dynamic_pressure(V) and multiply by CLA
    return dynamic_pressure(V) * CLA

print(dynamic_pressure(15.0))
print(downforce(15.0))

check("dynamic_pressure(15)", dynamic_pressure(15.0), 137.8125)
check("downforce(15)",        downforce(15.0),        482.34375)
check("downforce(25)",        downforce(25.0),        1339.84375)

speeds = [10, 15, 20, 25, 30]

for V in speeds:
    print(V, downforce(V))

speeds = [10, 15, 20, 25, 30]
weight = 300.0 * 9.81

print(f"{'V (m/s)':>8} {'q (Pa)':>10} {'F (N)':>10} {'% weight':>10}")
print("-" * 42)

for V in speeds:
    q   = dynamic_pressure(V)      # TODO: dynamic_pressure(V)
    F   = downforce(V)      # TODO: downforce(V)
    pct = 100 * F / weight      # TODO: 100 * F / weight
    print(f"{V:>8} {q:>10.1f} {F:>10.1f} {pct:>10.1f}")

packages = [("bare car", 0.3), ("WVU measured", 2.64),
            ("our placeholder", 3.5), ("aggressive", 4.0)]

for name, cla in packages:
    F   = 0.5 * rho * 15**2 * cla
    pct = 100 * F /weight
    print(f"  {name:<18} CLA={cla:<6} F={F:>7.1f} N   {pct:>5.1f}% of weight")

V_range = np.linspace(0, 30, 400)

F_range   = downforce(V_range)
pct_range = 100 * F_range / weight

plt.figure(figsize=(7, 4))
plt.plot(V_range, pct_range, linewidth=2, color="#7B2D26")
plt.xlabel("Speed (m/s)")
plt.ylabel("Downforce (% of car weight)")
plt.title("Downforce vs speed")
plt.grid(alpha=0.3)
plt.show()

print(V_range[:5])
print(pct_range[:5])
print("at 15 m/s:", 100 * downforce(15.0) / weight)

plt.figure(figsize=(7, 4))


plt.axvspan(12, 18, color="#eceaea", alpha=0.8)
plt.plot(V_range, pct_range, linewidth=2, color="#7B2D26")
plt.xlabel("Speed (m/s)")
plt.ylabel("Downforce (% of car weight)")
plt.title("Downforce vs speed, with the FSAE operating band")
plt.grid(alpha=0.3)
plt.show()

V0 = 15.0

for h in [1.0, 0.1, 0.01, 0.001, 0.0001]:
    slope = (downforce(V0 + h) - downforce(V0)) / h
    print(f"h = {h:<8}  slope = {slope}")

def dF_dV(V):
    return rho * CLA * V

print("exact derivative at V = 15:", dF_dV(15.0))

check("dF/dV at 15 m/s", dF_dV(15.0), 64.3125)
check("dF/dV at 10 m/s", dF_dV(10.0), 42.875)
check("dF/dV at 25 m/s", dF_dV(25.0), 107.1875)

exact = dF_dV(V0)

print(f"{'h':<12} {'approx slope':<20} {'error':<20}")
print("-" * 54)
for h in [1e-2, 1e-4, 1e-6, 1e-8, 1e-10, 1e-12, 1e-14]:
    slope = (downforce(V0 + h) - downforce(V0)) / h
    print(f"{h:<12} {slope:<20.10f} {abs(slope - exact):<20.12f}")

plt.figure(figsize=(7, 4))
plt.plot(V_range, dF_dV(V_range), color="#7B2D26", linewidth=2)
plt.xlabel("Speed (m/s)")
plt.ylabel("dF/dV  (N per m/s)")
plt.title("Rate of change of downforce with speed")
plt.grid(alpha=0.3)
plt.show()

fig, ax = plt.subplots(figsize=(7.5, 4.5))

ax.axvspan(12, 18, color="#eceaea", zorder=0)
ax.plot(V_range, pct_range, color="#7B2D26", linewidth=2, zorder=3)

for V_pt, label in [(10, "hairpin"), (15, "cruise"), (25, "fast sweeper")]:
    p = 100 * downforce(V_pt) / weight
    ax.plot([V_pt], [p], "o", color="#7B2D26", markersize=6,
            markeredgecolor="white", markeredgewidth=1.5, zorder=4)
    ax.annotate(f"{label}\n{V_pt*3.6:.0f} km/h\n{p:.0f}% of weight",
                xy=(V_pt, p), xytext=(V_pt - 1.5, p + 14),
                ha="right", fontsize=9,
                arrowprops=dict(arrowstyle="-", color="#888", linewidth=0.8))

ax.set_xlim(0, 30)
ax.set_ylim(0, 105)
ax.set_xlabel("Speed (m/s)")
ax.set_ylabel("Downforce (% of car weight)")
ax.set_title("Downforce vs speed — $C_L A$ = 3.5 m$^2$, 300 kg car")
ax.grid(axis="y", alpha=0.3)
ax.set_axisbelow(True)
for side in ("top", "right"):
    ax.spines[side].set_visible(False)

plt.tight_layout()
plt.show()

"""Beginning of Rung 2"""

import numpy as np
import matplotlib.pyplot as plt

rho = 1.225     # air density, kg/m^3
m   = 300.0     # car + driver, kg
g   = 9.81
CLA = 3.5       # C_L * A, m^2
R   = 15.0      # corner radius, m
mu  = 1.4       # tire friction coefficient

def downforce(v):
    return 0.5 * rho * v**2 * CLA

print("setup ok, downforce at 15 m/s =", downforce(15.0))

def a_tire(v):
    return mu * (m*g + downforce(v)) / m

def a_req(v):
    return v**2 / R


print("at 10 m/s:  tires can give", a_tire(10.0), " corner demands", a_req(10.0))
print("at 20 m/s:  tires can give", a_tire(20.0), " corner demands", a_req(20.0))

v = np.linspace(0, 22, 400)

plt.figure(figsize=(7.2, 4.2))
plt.plot(v, a_tire(v), color="#7B2D26", linewidth=2, label="what the tires can deliver")
plt.plot(v, a_req(v),  color="#2E5266", linewidth=2, label="what the corner demands")
plt.xlim(0, 22)
plt.ylim(0, 30)
plt.xlabel("Speed through the corner (m/s)")
plt.ylabel("Lateral acceleration (m/s$^2$)")
plt.title("Cornering: supply vs demand, R = 15 m")
plt.grid(alpha=0.3)
plt.legend(frameon=False)
plt.show()

def f(v):
    return a_tire(v) - a_req(v)

for test_v in [10, 14, 15, 16, 20]:
    print(f"f({test_v}) = {f(test_v):+.4f}")

plt.figure(figsize=(7.2, 3.6))
plt.plot(v, f(v), color="#7B2D26", linewidth=2)
plt.axhline(0, color="#888", linewidth=1)
plt.xlabel("Speed (m/s)")
plt.ylabel("f(v) = supply − demand")
plt.title("The root of f is the corner speed")
plt.grid(alpha=0.3)
plt.show()

lo, hi = 15.0, 16.0
mid = (lo + hi) / 2

print("f(lo)  =", f(lo))
print("f(mid) =", f(mid))
print("f(hi)  =", f(hi))
print("product f(lo)*f(mid) =", f(lo) * f(mid))

lo, hi = 15.0, 16.0

print(f"{'step':>4} {'lo':>12} {'mid':>12} {'hi':>12} {'f(mid)':>14} {'width':>12}")

for i in range(1, 9):
    mid = (lo+hi)/2
    fm  = f(mid)
    print(f"{i:>4} {lo:>12.6f} {mid:>12.6f} {hi:>12.6f} {fm:>+14.8f} {hi-lo:>12.6f}")

    if f(lo) * fm < 0:
        hi = mid        # sign change is in the lower half
    else:
        lo = mid        # sign change is in the upper half

lo, hi = 15.0, 16.0
for i in range(20):
    mid = (lo + hi) / 2
    if f(lo) * f(mid) < 0:
        hi = mid
    else:
        lo = mid

print(f"after 20 steps: v = {(lo+hi)/2:.8f}   bracket width = {hi-lo:.3e}")

def fp(v):
    return mu*rho*CLA*v/m - 2*v/R

for v in (10.0, 15.0, 20.0):
    num = (f(v + 1e-6) - f(v - 1e-6)) / 2e-6
    print(f"v={v:>5}  analytic = {fp(v):>12.8f}   numerical = {num:>12.8f}")

TRUE = 15.5686392510

print(f"{'step':>4} {'v':>16} {'f(v)':>18} {'error':>12}")
v = 10.0
for i in range(6):
    print(f"{i:>4} {v:>16.10f} {f(v):>+18.12f} {abs(v-TRUE):>12.2e}")
    v = v - f(v)/fp(v)

v = -5.0
for i in range(5):
    print(f"step {i}: v = {v:.8f}")
    v = v - f(v)/fp(v)

def closed_form(R):
    denom = 1 - R*mu*rho*CLA/(2*m)
    return (R*mu*g/denom)**0.5

print(repr(closed_form(15.0)))

def newton(R, v0=15.0, n=40):
    v = v0
    for _ in range(n):
        v = v - f(v)/fp(v)
    return v

c, nw = closed_form(15.0), newton(15.0)
print(f"closed form : {c!r}")
print(f"newton      : {nw!r}")
print(f"difference  : {abs(c-nw):.3e}")

print(f"{'R (m)':>8} {'denominator':>14} {'v (m/s)':>12} {'km/h':>9}")
for R in (5, 10, 15, 25, 50, 80, 95, 99, 99.9, 100, 120):
    d = 1 - R*mu*rho*CLA/(2*m)
    if d <= 0:
        print(f"{R:>8} {d:>14.6f} {'no solution':>12} {'--':>9}")
    else:
        v = (R*mu*g/d)**0.5
        print(f"{R:>8} {d:>14.6f} {v:>12.3f} {v*3.6:>9.1f}")

mu0 = 1.4
n   = 0.15
W   = m*g

def mu_of(v):
    Fz = W + downforce(v)
    return mu0 * (Fz/W)**(-n)

for v in (0, 10, 15, 20, 25, 30):
    print(f"v={v:>3} m/s   load = {W+downforce(float(v)):>8.1f} N   mu = {mu_of(float(v)):.4f}")

def f2(v, R):
    return mu_of(v)*(W + downforce(v))/m - v**2/R

def fp2(v, R, h=1e-6):
    return (f2(v+h, R) - f2(v-h, R)) / (2*h)

v = 15.0
for i in range(5):
    print(f"step {i}: v = {v:.8f}   f2 = {f2(v,15.0):+.10f}")
    v = v - f2(v,15.0)/fp2(v,15.0)

def newton2(R, v0=15.0, it=60):
    v = v0
    for _ in range(it):
        v = v - f2(v,R)/fp2(v,R)
    return v

for R in (15, 50, 95, 100, 120, 200, 500, 1000):
    print(f"R = {R:>5}  ->  v = {newton2(float(R)):>10.3f}")

v = newton2(200.0)
print(f"v = {v:.3f}   f2(v) = {f2(v,200.0):.5f}")

def newton_safe(R, v0=15.0, tol=1e-10, maxit=100):
    v = v0
    for i in range(maxit):
        d = fp2(v, R)
        if d == 0:
            return v, i, False
        step = f2(v, R)/d
        v -= step
        if abs(step) < tol:
            return v, i+1, True
    return v, maxit, False

for R in (15, 50, 120, 200, 500, 1000):
    v, it, ok = newton_safe(float(R))
    print(f"R = {R:>5}  v = {v:>10.3f}  iters = {it:>4}  converged = {ok}")

import numpy as np

v0, a, L = 10.0, 3.0, 100.0

v_end   = (v0**2 + 2*a*L)**0.5
T_exact = (v_end - v0)/a

print(f"v_end   = {v_end!r}")
print(f"T exact = {T_exact!r}")

def v_of(s):
    return (v0**2 + 2*a*s)**0.5

def left_riemann(N):
    s  = np.linspace(0, L, N+1)   # N+1 edges -> N pieces
    ds = L/N
    return np.sum(ds / v_of(s[:-1]))     # s[:-1] drops the last edge

for N in (10, 100, 1000, 10000):
    T = left_riemann(N)
    print(f"N = {N:>6}   T = {T:.9f}   error = {abs(T-T_exact):.2e}")

def trapezoid(N):
    s = np.linspace(0, L, N+1)
    f = 1.0/v_of(s)
    return np.trapezoid(f, s)     # older NumPy: np.trapz(f, s)

import numpy as np
import matplotlib.pyplot as plt

rho, m, g = 1.225, 300.0, 9.81
CLA, CDA  = 3.5, 1.3
mu0, n    = 1.4, 0.15
W = m*g

def downforce(v): return 0.5*rho*v**2*CLA
def mu_of(v):     return mu0 * ((W + downforce(v))/W)**(-n)
def f2(v, R):     return mu_of(v)*(W + downforce(v))/m - v**2/R
def fp2(v, R, h=1e-6): return (f2(v+h,R) - f2(v-h,R))/(2*h)

def corner_speed(R, v0=15.0, tol=1e-10, maxit=100):
    if R is None:
        return 1e4                  # a straight: no cornering limit
    v = v0
    for i in range(maxit):
        d = fp2(v, R)
        if d == 0:
            return None
        step = f2(v, R)/d
        v -= step
        if abs(step) < tol:
            return v
    return None                     # did not converge

TRACK = [
    ("straight", 75.0, None),
    ("corner",   23.6, 15.0),
    ("straight", 40.0, None),
    ("corner",   31.4, 10.0),
    ("straight", 60.0, None),
    ("corner",   39.3, 25.0),
    ("straight", 50.0, None),
    ("corner",   25.1,  8.0),     # the hairpin
    ("straight", 90.0, None),
    ("corner",   47.1, 30.0),
    ("straight", 40.0, None),
    ("corner",   37.7, 12.0),
]

print("total length =", sum(seg[1] for seg in TRACK), "m")

def build_track(ds=0.5):
    s_list, R_list = [], []
    pos = 0.0
    for kind, length, radius in TRACK:
        n_steps = max(int(round(length/ds)), 1)
        for k in range(n_steps):
            s_list.append(pos)
            R_list.append(radius)
            pos += length/n_steps
    return np.array(s_list), R_list, pos

S, R, total = build_track(0.5)
print(f"built {len(S)} points, total {total:.1f} m")
print("first 6 positions:", S[:6])

v_limit = np.array([corner_speed(r) for r in R])

print("corner-limited points:", np.sum(v_limit < 1e3), "of", len(v_limit))
print("slowest point on track:", v_limit.min(), "m/s")

for Rc in (8.0, 10.0, 12.0, 15.0, 25.0, 30.0):
    v = corner_speed(Rc)
    print(f"R = {Rc:>5} m   v = {v:>7.3f} m/s   ({v*3.6:>5.1f} km/h)")

import numpy as np
import matplotlib.pyplot as plt

# ---- car ----
rho, m, g = 1.225, 300.0, 9.81
CLA, CDA  = 3.5, 1.3
mu0, n    = 1.4, 0.15
W = m*g

def downforce(v): return 0.5*rho*v**2*CLA
def mu_of(v):     return mu0 * ((W + downforce(v))/W)**(-n)
def f2(v, R):     return mu_of(v)*(W + downforce(v))/m - v**2/R
def fp2(v, R, h=1e-6): return (f2(v+h,R) - f2(v-h,R))/(2*h)

def corner_speed(R, v0=15.0, tol=1e-10, maxit=100):
    if R is None:
        return 1e4
    v = v0
    for i in range(maxit):
        d = fp2(v, R)
        if d == 0:
            return None
        step = f2(v, R)/d
        v -= step
        if abs(step) < tol:
            return v
    return None

# ---- track ----
TRACK = [
    ("straight", 75.0, None),
    ("corner",   23.6, 15.0),
    ("straight", 40.0, None),
    ("corner",   31.4, 10.0),
    ("straight", 60.0, None),
    ("corner",   39.3, 25.0),
    ("straight", 50.0, None),
    ("corner",   25.1,  8.0),
    ("straight", 90.0, None),
    ("corner",   47.1, 30.0),
    ("straight", 40.0, None),
    ("corner",   37.7, 12.0),
]

def build_track(ds=0.5):
    s_list, R_list = [], []
    pos = 0.0
    for kind, length, radius in TRACK:
        n_steps = max(int(round(length/ds)), 1)
        for k in range(n_steps):
            s_list.append(pos)
            R_list.append(radius)
            pos += length/n_steps
    return np.array(s_list), R_list, pos

S, R, total = build_track(0.5)
v_limit = np.array([corner_speed(r) for r in R])

print(f"track length   : {total:.1f} m")
print(f"points         : {len(S)}")
print(f"corner-limited : {np.sum(v_limit < 1e3)} of {len(v_limit)}")
print(f"slowest point  : {v_limit.min():.3f} m/s")

v_plot = np.where(v_limit > 1e3, np.nan, v_limit)

fig, ax = plt.subplots(figsize=(8, 3.8))
pos = 0.0
for kind, L, r in TRACK:
    if kind == "corner":
        ax.axvspan(pos, pos+L, color="#f2f0ef", zorder=0)
    pos += L
ax.plot(S, v_plot, color="#7B2D26", linewidth=1.8, label="with aero")
ax.set_xlim(0, total); ax.set_ylim(6, 26)
ax.set_xlabel("Distance around the lap (m)")
ax.set_ylabel("Corner speed limit (m/s)")
ax.grid(axis="y", alpha=0.3); ax.legend(frameon=False)
plt.tight_layout()
plt.show()

P = 80e3     # FSAE EV power limit, watts

def drag(v):       return 0.5*rho*v**2*CDA
def a_traction(v): return mu_of(v)*(W + downforce(v))/m
def a_power(v):    return P/(m*max(v, 0.5))
def a_accel(v):    return min(a_traction(v), a_power(v)) - drag(v)/m

print(f"{'v (m/s)':>8} {'traction':>10} {'power':>10} {'drag':>8} {'net':>10} {'limited by':>12}")
for v in (5, 10, 15, 17, 20, 25, 30, 35):
    at, ap, ad = a_traction(float(v)), a_power(float(v)), drag(float(v))/m
    lim = "traction" if at < ap else "power"
    print(f"{v:>8} {at:>10.3f} {ap:>10.3f} {ad:>8.3f} {a_accel(float(v)):>10.3f} {lim:>12}")

ds    = total/len(S)
start = int(np.argmin(v_limit))
print(f"slowest point: index {start}, s = {S[start]:.1f} m, v = {v_limit[start]:.3f} m/s")

order = np.roll(np.arange(len(S)), -start)   # visit order, starting at the hairpin
v_fwd = v_limit.copy()

for k in range(1, len(order)):
    i, j = order[k-1], order[k]
    reachable = (v_fwd[i]**2 + 2*a_accel(v_fwd[i])*ds)**0.5
    v_fwd[j]  = min(v_limit[j], reachable)

print(f"max speed reached: {v_fwd.max():.3f} m/s ({v_fwd.max()*3.6:.1f} km/h)")
print(f"acceleration-limited points: {np.sum(v_fwd < v_limit - 1e-9)} of {len(S)}")

fig, ax = plt.subplots(figsize=(8, 4))
pos = 0.0
for kind, L, r in TRACK:
    if kind == "corner":
        ax.axvspan(pos, pos+L, color="#f2f0ef", zorder=0)
    pos += L
ax.plot(S, np.where(v_limit > 1e3, np.nan, v_limit),
        color="#2E5266", lw=1.6, ls="--", label="corner limit")
ax.plot(S, v_fwd, color="#7B2D26", lw=1.9, label="after forward pass")
ax.set_xlim(0, total); ax.set_ylim(5, 42)
ax.set_xlabel("Distance around the lap (m)")
ax.set_ylabel("Speed (m/s)")
ax.grid(axis="y", alpha=0.3); ax.legend(frameon=False)
plt.tight_layout(); plt.show()

def a_brake(v):
    return a_traction(v) + drag(v)/m

print(f"{'v (m/s)':>8} {'tyre':>9} {'drag':>8} {'total':>9} {'in g':>7}")
for v in (10, 15, 20, 25, 30, 37):
    print(f"{v:>8} {a_traction(float(v)):>9.3f} {drag(float(v))/m:>8.3f} "
          f"{a_brake(float(v)):>9.3f} {a_brake(float(v))/9.81:>7.2f}")

v = v_fwd.copy()

for k in range(len(order)-1, 0, -1):
    j, i = order[k], order[k-1]
    v[i] = min(v[i], (v[j]**2 + 2*a_brake(v[j])*ds)**0.5)

print(f"max speed: forward {v_fwd.max():.3f}  ->  final {v.max():.3f} m/s")
print(f"braking-limited points: {np.sum(v < v_fwd - 1e-9)} of {len(S)}")

T = np.sum(ds/v)
print(f"lap time: {T:.4f} s")
print(f"average speed: {total/T:.2f} m/s ({total/T*3.6:.1f} km/h)")

for it in range(1, 5):
    for k in range(1, len(order)):
        i, j = order[k-1], order[k]
        v[j] = min(v[j], (v[i]**2 + 2*a_accel(v[i])*ds)**0.5)
    for k in range(len(order)-1, 0, -1):
        j, i = order[k], order[k-1]
        v[i] = min(v[i], (v[j]**2 + 2*a_brake(v[j])*ds)**0.5)
    print(f"pass {it}: T = {np.sum(ds/v):.4f} s")

fig, ax = plt.subplots(figsize=(8, 4))
pos = 0.0
for kind, L, r in TRACK:
    if kind == "corner":
        ax.axvspan(pos, pos+L, color="#f2f0ef", zorder=0)
    pos += L
ax.plot(S, v_fwd, color="#a89b8c", lw=1.4, ls="--", label="forward pass only")
ax.plot(S, v, color="#7B2D26", lw=2.0, label="final speed profile")
ax.set_xlim(0, total); ax.set_ylim(5, 42)
ax.set_xlabel("Distance around the lap (m)")
ax.set_ylabel("Speed (m/s)")
ax.set_title(f"Final velocity profile — lap time {T:.3f} s")
ax.grid(axis="y", alpha=0.3); ax.legend(frameon=False)
plt.tight_layout(); plt.show()

import numpy as np

rho, g, mu0, n_ = 1.225, 9.81, 1.4, 0.15
P = 80e3

def simulate(CLA=3.5, CDA=1.3, m=300.0, ds_target=0.5):
    S, R, total = build_track(ds_target)
    ds = total/len(S)
    W  = m*g

    DF = lambda v: 0.5*rho*v*v*CLA
    DR = lambda v: 0.5*rho*v*v*CDA
    mu = lambda v: mu0*((W+DF(v))/W)**(-n_)
    f2 = lambda v, Rr: mu(v)*(W+DF(v))/m - v*v/Rr

    def cs(Rr, v0=15., tol=1e-10, it=100):
        if Rr is None: return 1e4
        v = v0
        for _ in range(it):
            h = 1e-6
            d = (f2(v+h,Rr) - f2(v-h,Rr))/(2*h)
            if d == 0: return None
            st = f2(v,Rr)/d
            v -= st
            if abs(st) < tol: return v
        return None

    vl = np.array([cs(r) for r in R])
    at = lambda v: mu(v)*(W+DF(v))/m
    aa = lambda v: min(at(v), P/(m*max(v,.5))) - DR(v)/m
    ab = lambda v: at(v) + DR(v)/m

    start = int(np.argmin(vl))
    order = np.roll(np.arange(len(S)), -start)
    v = vl.copy()
    for k in range(1, len(order)):
        i, j = order[k-1], order[k]
        v[j] = min(v[j], (v[i]**2 + 2*aa(v[i])*ds)**0.5)
    for k in range(len(order)-1, 0, -1):
        j, i = order[k], order[k-1]
        v[i] = min(v[i], (v[j]**2 + 2*ab(v[j])*ds)**0.5)

    T = np.sum(ds/v)

    a_act = np.zeros_like(v)
    for k in range(len(order)):
        i, j = order[k], order[(k+1) % len(order)]
        a_act[i] = (v[j]**2 - v[i]**2)/(2*ds)
    E = np.sum(np.maximum(0.0, m*a_act + DR(v))*ds)

    return dict(T=T, v=v, S=S, total=total, vmax=v.max(), E_kWh=E/3.6e6, ds=ds)

base = simulate(CLA=0.0, CDA=0.8, m=300.0)
aero = simulate(CLA=3.5, CDA=1.3, m=320.0)
free = simulate(CLA=3.5, CDA=1.3, m=300.0)   # mass penalty removed, to isolate it

for nm, r in [("no aero, 300 kg", base), ("aero, 320 kg", aero), ("aero, no mass penalty", free)]:
    print(f"{nm:<24}{r['T']:>9.3f} s{r['vmax']:>9.2f} m/s{r['E_kWh']:>11.5f} kWh")

base = simulate(CLA=0.0, CDA=0.8, m=300.0)
for CLA in (1.0, 1.5, 2.0, 2.64, 3.0, 3.5, 4.0):
    r = simulate(CLA=CLA, CDA=0.8+0.143*CLA, m=300.0+5.7*CLA)
    print(f"CLA={CLA:>5}  lap {r['T']:>8.3f} s   gain {base['T']-r['T']:>+7.3f} s   E {r['E_kWh']:.4f}")

for ds in (2.0, 1.0, 0.5, 0.25, 0.125, 0.0625):
    b = simulate(CLA=0.0, CDA=0.8, m=300.0, ds_target=ds)['T']
    a = simulate(CLA=3.5, CDA=1.3, m=320.0, ds_target=ds)['T']
    print(f"ds = {ds:>7} m   no aero {b:>8.4f}   aero {a:>8.4f}   gain {b-a:.4f}")